command:
  - "gunicorn"
  - "main:app"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"

env:
  - name: SERVING_ENDPOINT_NAME
    value: databricks-claude-sonnet-4-5
  - name: DATABRICKS_HOST
    value: adb-1108746899088703.3.azuredatabricks.net
  - name: GENIE_SPACE_ID
    value: "01f0eaaeedaf11b7b236db1eb5bbd243"
  - name: GENIE_SPACE_NAME
    value: "genie-client-background"
