command:
  - "gunicorn"
  - "main:app"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"

env:
  # SERVING_ENDPOINT_NAME is now optional - endpoints can be selected dynamically via UI
  # Uncomment below to set a default endpoint
  # - name: SERVING_ENDPOINT_NAME
  #   value: databricks-claude-sonnet-4-5
  - name: DATABRICKS_HOST
    value: adb-1108746899088703.3.azuredatabricks.net
